project/app1/urls.py
from django.urls import path
from .views import index, log,card,verifyDoc,logout,registration, verifiedDocument,errorpage,confirm,forgotpassword

urlpatterns = [
    path('index/', index, name="index"),
    path('', registration, name="regi"),
    path('login/', log, name="login"),
    path('verify_document/', verifyDoc, name="verifyDoc"),
    path('logout/', logout, name="logout"),
    path('documents/', verifiedDocument, name="verifiedDoc"),
    path('card/',card,name="card"),
    path('error/',errorpage,name="error"),
    path('confirm/',confirm,name = 'confirm'),
    path('forgotpassword/',forgotpassword,name = 'forgotpassword')

]

project/digita/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.AUDIO_URL,
                          document_root=settings.AUDIO_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/app1/models.py
from django.db import models
import uuid
# Create your models here.


class LoginForm(models.Model):
    username = models.CharField(
        "Enter Your Full Name", max_length=20, default="")
    dob = models.CharField(max_length = 50)
    gender = models.CharField(max_length=1,
                              choices=(
                                  ('M', "Male"),
                                  ('F', "Female"),
                                  ('O', "Other"),
                              ), default="M",
                              )
    mobile = models.PositiveIntegerField(default='')
    email = models.EmailField(default="")
    password = models.CharField(default="", max_length=12)
    confirm_password = models.CharField(default="", max_length=12)
    hint = models.CharField(max_length = 50,blank = True,default = 'user')
    unique = models.UUIDField(default=uuid.uuid4, editable=True,blank = True)
    status = models.BooleanField(verbose_name="Access:",default = False)

    def __str__(self):
        return self.username


class VerifyDocument(models.Model):
    user_data = models.ForeignKey(LoginForm,on_delete=models.CASCADE, default="")
    doc_no = models.CharField(default="", max_length=12, unique=True)
    doc_name = models.CharField(max_length=20,
                                choices=(
                                    ("Adhaar Card", "Adhaar Card"),
                                    ("Driving License", "Driving License"),
                                    ("PAN Card", "PAN Card"),
                                    ("Vehicle RC", "Vehicle RC"),
                                ), default="Adhaar Card",
                                )
    doc_upload_front = models.ImageField(upload_to="media/", blank=True)
    doc_upload_back = models.ImageField(upload_to="media/", blank=True)
    qrcode = models.ImageField(upload_to = 'media/',blank = True, default="")


    def __str__(self):
        return self.doc_no + " | " + self.doc_name 

class feedback(models.Model):
    name = models.CharField(
        "Enter Your Full Name", max_length=20, default="")
    email = models.EmailField(default="")
    message = models.TextField(default="")

    def __str__(self):
        return self.email + " | " + self.message

project/app1/forms.py
from django import forms
from app1.models import LoginForm,VerifyDocument, feedback

CATEGORIES = (  
    ('G','Gender'),
    ('M', "Male"),
    ('F', "Female"),
    ('O', "Other"),
)

class LoginField(forms.ModelForm):
    class Meta:
        model = LoginForm
        fields = '__all__'

class VerifyDocumentForm(forms.Form):
    
    Doc_No = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control','id':'docno','placeholder':'Document Number', 'autofocus':'autofocus','required': True}))
    Front_image = forms.ImageField(widget = forms.FileInput(attrs={'class':'form-control','id':'front_image','name':'front_image','autofocus':'autofocus'}))
    Back_image = forms.ImageField(widget = forms.FileInput(attrs={'class':'form-control','id':'back_image','name':'back_image','autofocus':'autofocus'}))
    
class RegistrationForm(forms.ModelForm):
        class Meta:
            model = LoginForm
            fields = ['username','dob','gender','mobile','email','password','hint']

class feedbackForm(forms.ModelForm):
    class Meta:
        model = feedback
        fields = ['name','email','message']
        

project/app1/views.py
from django.shortcuts import render, redirect
from django.http import request,HttpResponseRedirect,HttpResponse
from .models import LoginForm, VerifyDocument,feedback
from .forms import LoginField, VerifyDocumentForm, RegistrationForm, feedbackForm
import qrcode
import os
from digita.settings import BASE_DIR
from django.contrib import messages
import uuid
# Create your views here.

def index(request):
      if 'user' in request.session:
            print("Hello")
            user = LoginForm.objects.get(email=request.session['user'])
            print(user)
            if request.POST:
                  name= request.POST['name']
                  email = request.POST['email']
                  message = request.POST['message'] 

                  obj = feedback()
                  obj.name = name
                  obj.email = email
                  obj.message = message
                  obj.save()
                  return redirect('index')
            else:
                  return render(request,'index.html',{'user':user.username}) 
            return render(request,'index.html')
      else:
            return redirect('login')

def logout(request):
  if request.session.keys():
        del request.session['user']
        return redirect('login')
        
def log(request):
  if request.method=="POST":
        try:
            m = LoginForm.objects.get(username=request.POST['username'])
            if m.password == request.POST['password']:
                request.session['user'] = m.email
                return HttpResponseRedirect('/index/')
            else:
                return HttpResponse("<h2><a href=''>You have entered wrong password </a></h2>")
        except:
            return HttpResponse("<h2><a href=''>no username found.</a></h2>")
  return render(request, 'log1.html')


def verifyDoc(request):
      if 'user' in request.session:
            user = LoginForm.objects.get(email=request.session['user'])
            if request.method=="POST":
                  try:
                        print(request.session['user'])
                        user = LoginForm.objects.get(email=request.session['user'])
                        m = VerifyDocument.objects.get(user_data=user,doc_no=request.POST['doc_no'])
                        print(m.doc_name)
                        print(m.doc_no)
                        if m.doc_name == request.POST['doc_name']:
                              print("dd")
                              if m.qrcode != '':
                                    return HttpResponse("<h2><a href=''>already verified</a></h2>")
                              name = user.username+"_"+m.doc_name
                              data = "User Name = "+user.username+"\nDocument name = "+m.doc_name+"\nDocument No = "+str(m.doc_no)
                              qr=qrcode.QRCode(version=1,box_size=10,border=5)
                              qr.add_data(data)
                              print("ee")
                              qr.make(fit=True)
                              img=qr.make_image(fill="black",back_color="white")
                              img.save(os.path.join(BASE_DIR,"media/"+ name +".jpeg"))
                              m.qrcode = name +".jpeg"
                              m.save()

                              return render(request,'document_very1.html',{'m':m,'user':user.username})
                        else:
                              return HttpResponse("<h2><a href=''>You have entered wrong details </a></h2>")
                  except:
                        return redirect('error')
            return render(request, 'document_very.html',{'user':user})
      else:
            return redirect('login')

def verifiedDocument(request):
      if 'user' in request.session:
            user = LoginForm.objects.get(email=request.session['user'])
            data = VerifyDocument.objects.filter(user_data=user)
            print(data)
            li = []
            for i in data:
                  if i.qrcode != '':
                        print(i)
                        li.append(i)
            return render(request,'verified_doc.html',{'li':li, 'user':user})   
      else:
            return redirect('login')      
            
def registration(request):
  if request.POST:
    username = request.POST['username']
    email = request.POST['email']
    mobile = request.POST['mobile']
    gender = request.POST['gender']
    dddd = request.POST['birthday']
    password = request.POST['password']
    conf_pass = request.POST['conf_password']
    hint = request.POST['hint']

    obj = LoginForm()
    obj.username = username
    obj.dob = dddd
    obj.gender = gender
    obj.email = email 
    obj.mobile = mobile
    obj.password = password
    obj.confirm_password = conf_pass
    obj.hint = hint
    
    obj.save()
    return redirect('index')
  else:
    return render(request,'registeration1.html')

def Feedback(request):
      if request.POST:
            name= request.POST['name']
            email = request.POST['email']
            message = request.POST['message'] 
            obj = feedback()
            obj.name = name
            obj.email = email
            obj.message = message
            obj.save()
            return redirect('index')
      else:
            return render(request,'index.html') 

def card(request):
      if 'user' in request.session:
            user = LoginForm.objects.get(email=request.session['user'])
            m=user.unique
            if user.status ==True:
                  return render(request,'card.html',{'m':m,'user':user})
            else:
                  return redirect('error')        
               
      else:
            return redirect('login') 

def errorpage(request):
      return render(request,'error.html')

def confirm(request):
      if request.method == 'POST':
            try:
                  model = LoginForm.objects.get(username = request.POST['username'])
                  if model.hint == request.POST['hint']:
                        request.session['forgot'] = model.username
                        return redirect('forgotpassword')
                  else:
                        return HttpResponse("<a href = ''>Your Hint is Wrong</a>")
            except:
                  return HttpResponse("<a href = ''>Please Enter Correct Username</a>")
      return render(request,'confirm.html')

def forgotpassword(request):
      if request.method == 'POST':
            try:
                  username = request.session['forgot']
                  model = LoginForm.objects.get(username = username)
                  password = request.POST['password']
                  conf_password = request.POST['password1']
                  model.password = password
                  model.confirm_password = conf_password
                  model.save()
                  return redirect('login')
            except:
                  return HttpResponse("<a href = ''>Something Went Wrong</a>")
      return render(request,'forgot-password.html')

project/app1/templates/Upload_Docs.html
<!DOCTYPE html>
<html>
<body>
    
{% if adhaar %}
    <form method="POST" action="{% url 'Add' %}" enctype="multipart/form-data">
        <h1>Adhaar Card</h1>
        {% csrf_token %}
            {{ adhaar.as_p }}       
            <input type="hidden" name="doc_name"  onblur="AadharValidate();" value="Adhaar Card">
        <input type="submit" value="submit">
    </form>
{% elif drive %}
    <form method="POST" action="{% url 'Add' %}" enctype="multipart/form-data">
        <h1>Driving License</h1>
        {% csrf_token %}
            {{ drive.as_p }}       
            <input type="hidden" name="doc_name" value="Driving License">
        <input type="submit" value="submit">
    </form>
{% elif pan %}
    <form method="POST" action="{% url 'Add' %}" enctype="multipart/form-data">
        <h1>PAN Card</h1>
        {% csrf_token %}
            {{ pan.as_p }}       
            <input type="hidden" name="doc_name" value="PAN Card">
        <input type="submit" value="submit">
    </form>
{% elif vehical %}
    <form method="POST" action="{% url 'Add' %}" enctype="multipart/form-data">
        <h1>Vehicle RC</h1>
        {% csrf_token %}
            {{ vehical.as_p }}     
            <input type="hidden" name="doc_name" value="Vehicle RC">
        <input type="submit" value="submit">
    </form>
{% else %}
    <form method="POST">
        {% csrf_token %}
        <label for="Docs">Select Your Document Type To Upload :</label>
            <select id="Docs" name="Docs">
                <option value="Adhaar Card" selected>Adhaar Card</option>
                <option value="Driving License">Driving License</option>
                <option value="PAN Card">PAN Card</option>
                <option value="Vehicle RC">Vehicle RC</option>
            </select>
            <input type="submit" value="Submit">
    </form>
{% endif %}
<script type="text/javascript">
    function AadharValidate() {
        var aadhar = document.getElementById("txtAadhar").value;
        var adharcardTwelveDigit = /^\d{12}$/;
        var adharSixteenDigit = /^\d{16}$/;
        if (aadhar != '') {
            if (aadhar.match(adharcardTwelveDigit)) {
                return true;
            }
            else if (aadhar.match(adharSixteenDigit)) {
                return true;
            }
            else {
                alert("Enter valid Aadhar Number");
                return false;
            }
        }
    }
</script>
</body>
</html>

project/app1/templates/confirm.html
{% load static %}

<html lang="en">
<head>
  <title>Forgot Password</title>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 't/fonts/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 't/css/style2.css' %}">
</head>
<body>
<div class="wrapper">
  <div class="inner">
    <form name="form" method="POST">
      {% csrf_token %}
      <h3>Forgot Password</h3>
      <div class="form-holder">
        <label class="control-label col-sm-2" >Enter  username:</label>
        <span class="lnr lnr-user"></span>

        <input type="text" class="form-control" id="id_username" placeholder="Enter username" name="username">
      </div>
      <div class="form-holder">
        <label class="control-label col-sm-2" >Enter Hint:</label>
        <span class="lnr lnr-lock"></span>
        <input type="text" class="form-control" id="id_hint" placeholder="Enter Security Hint" name="hint">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
<script src="{% static 't/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 't/js/main.js' %}"></script>
</body>
</html>

project/app1/templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Forgot Password</title>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 't/fonts/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 't/css/style2.css' %}">
</head>
<body>
<div class="wrapper">
  <div class="inner">
    <form name="form" method="POST">
      {% csrf_token %}
      <h3>Forgot Password</h3>
      <div class="form-holder">
        <label class="control-label col-sm-2" for="pwd">Enter  Password:</label>
        <span class="lnr lnr-user"></span>

          <input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
      </div>
      <div class="form-holder">
        <label class="control-label col-sm-2" for="pwd">Enter Confirm Password:</label>
        <span class="lnr lnr-lock"></span>
        <input type="password" class="form-control" id="password1" placeholder="Enter confirm password" name="password1">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
<script src="{% static 't/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 't/js/main.js' %}"></script>
</body>
</html>

project/app1/templates/log1.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Loging</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 't/fonts/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 't/css/style2.css' %}">
</head>

<body>
	<div class="wrapper">
		<div class="inner">
			
			<form name="form" method="POST">
				{% csrf_token %}
				<h3><a href="/index.html/">Sign In</a></h3>
				<div class="form-holder">
					<span class="lnr lnr-user"></span>
					<input type="text" class="form-control" placeholder="Username" name="username"
						autofocus>
				</div>
				<div class="form-holder">
					<span class="lnr lnr-lock"></span>
					<input type="password" class="form-control" name="password"
						placeholder="Password">
				</div>
				<button>
					<span>Sign In</span>
				</button>
				<div style="text-align: center;margin-top: 30px;text-shadow: 0px 0px 3px">
					<a href="{% url 'regi' %}">Sign Up</a>
				</div>
				<div style="text-align: center;margin-top: 30px;text-shadow: 0px 0px 3px">
					<a href="{% url 'confirm' %}">Forgot Password?</a>
				</div>
			</form>
			<img src="{% static 't/images/image-2.png' %}" alt="" class="image-2">
		</div>
	</div>

	<script src="{% static 't/js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 't/js/main.js' %}"></script>


</body>

</html>

project/app1/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

project/app1/templates/registeration1.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Registration</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 't/fonts/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 't/css/style2.css' %}">
	
</head>

<body>

	<div class="wrapper">
		<div class="inner">
			<!-- <img src="{% static 'images/image-1.png' %}" alt="" class="image-1"> -->
			<form method="POST" onsubmit="return validation()">
				{% csrf_token %}

				<h3>Sign Up </h3>
				<!-- <div class="form-holder">
					<span class="lnr lnr-file-add"></span>
					 <select class="form-control" name >
							<option selected disabled>Select</option>
							<option>Mrs.</option>
							<option>Ms.</option>
							<option>Miss</option>
							<option>Dr.</option>
							<option>Mr.</option>
						</select> 
				</div> -->
				<div class="form-holder"><span id="username" style="color: red; margin-left: 50%; font-size: 12px; margin-top: 0%"></span>
					<span class="lnr lnr-user"></span>
					<input type="text" class="form-control" name="username" id="name"
						placeholder="Username">
						
				</div>
				
				
				<div class="form-holder">
					<span class="fa fa-birthday-cake"></span>
					<input class="form-control" placeholder="BIRTHDATE" name="birthday" data-date-format="YYYY-MM-DD" id="dob" autocomplete="off" style="background-color: transparent;" type="text" onfocus="(this.type='date')" onblur="(this.type='text') >
                                   
					<i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>

					<span id="date" style="color: red; margin-left: 50%; font-size: 12px;"></span>
				</div>
				<div class="form-holder">
						<span id="gen" style="color: red; margin-left: 0%; font-size: 12px;"></span>
					<span class="fa fa-globe" style="color: #9e9e9e"></span>
					<select class="form-control" id="gender" name="gender">
						<option disabled="disabled" selected="selected">GENDER</option>
						<option name="gender">Male</option>
						<option name="gender">Female</option>
						<option name="gender">Other</option>
					</select>
					
				</div>
				<div class="form-holder">
					<span class="lnr lnr-phone-handset"></span>
					<input type="text" class="form-control" name="mobile" id="mobile"
						placeholder="Phone_Number" maxlength="10">
						<span id="mob" style="color: red; margin-left: 50%; font-size: 12px;"></span>
				</div>
				<div class="form-holder">
					<span class="lnr lnr-envelope"></span>
					<input type="text" class="form-control" name="email" id="email" placeholder="Email">
					<span id="mail" style="color: red; margin-left: 70%; font-size: 12px;"></span>
				</div>
				<div class="form-holder">
					<span class="lnr lnr-lock"></span>
					<input type="password" class="form-control" name="password" id="password" placeholder="Password">
					<span id="pass" style="color: red; margin-left: 50%; font-size: 12px;"></span>
				</div>
				<div class="form-holder">
					<span class="lnr lnr-lock"></span>
					<input type="password" class="form-control" name="conf_password" id="confirm_password"
						placeholder="Confirm_Password">
						<span id="conpass" style="color: red; margin-left: 50%; font-size: 12px;"></span>
				</div>
				<div class="form-holder">
					<span class="lnr lnr-lock"></span>
					<input type="text" class="form-control" name="hint" id="id_hint"
						placeholder="Security Hint">
						<span id="conpass" style="color: red; margin-left: 50%; font-size: 12px;"></span>
				</div>
				
				<button  type="submit">
					<span>Sign Up</span>
				</button>
				<div style="text-align: center;margin-top: 30px;text-shadow: 0px 0px 3px">
					<a href="{% url 'login' %}">Already a user? LOGIN HERE</a>
				</div>
			</form>
			<img src="{% static 't/images/image-2.png' %}" alt="" class="image-2">
		</div>

	</div>

	<script src="{% static 't/js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 't/js/main.js' %}"></script>

	<!--form validation javascript-->
	<script type="text/javascript">
		function validation(){
				var name = document.getElementById('name').value;
				var dob = document.getElementById('dob').value;
				var mobile = document.getElementById('mobile').value;
				var email = document.getElementById('email').value;
				var gender = document.getElementById('gender').value;
				var password = document.getElementById('password').value;
				var confirm_password = document.getElementById('confirm_password').value;

				if(name==""){
						document.getElementById('username').innerHTML = "** Please fill the NAME field";
						return false;
				}
				if(!isNaN(name)){
						document.getElementById('username').innerHTML = "** Only Characters are allowed";
						return false;
				}
				if((name.length <=2) || (name.length >40)){
						document.getElementById('username').innerHTML = "** Name length must be between 2 to 40";
						return false;
				}
				
				if(dob==""){
						document.getElementById('date').innerHTML = "** Please fill the DOB field";
						return false;
				}
				if(gender==""){
						document.getElementById('gen').innerHTML = "** Please fill the GENDER field";
						return false;
				}
				if(mobile==""){
						document.getElementById('mob').innerHTML = "** Please fill the MOBILE NUMBER field";
						return false;
				}
				if(isNaN(mobile)){
						document.getElementById('mob').innerHTML = "** Only Numbers are allowed";
						return false;
				}
				if(mobile.length != 10){
						document.getElementById('mob').innerHTML = "** Enter correct Mobile Number having 10 digits";
						return false;
				}
				if(email==""){
						document.getElementById('mail').innerHTML = "** Please fill the EMAIL ID field";
						return false;
				}
				if(email.indexOf('@') <=0){
						document.getElementById('mail').innerHTML = "** Invalid email id (@ should not be at 1st position)";
						return false;
				}
				if((email.charAt(email.length-4)!='.') && (email.charAt(email.length-3)!='.')){
						document.getElementById('mail').innerHTML = "** Invalid email id ";
						return false;
				}
				if(password==""){
						document.getElementById('pass').innerHTML = "** Please fill the PASSWORD field";
						return false;
				}
				if((password.length <=5) || (password.length >10)){
						document.getElementById('pass').innerHTML = "** Password length must be between 6 to 10";
						return false;
				}
				if(password != confirm_password){
						document.getElementById('conpass').innerHTML = "** Password doesnt match";
						return false;
				}
				if(confirm_password==""){
						document.getElementById('conpass').innerHTML = "** Please fill the CONFIRM PASSWORD field";
						return false;
				}
				
				
		}
</script>

</body>

</html>